# Generated by Django 4.0.4 on 2022-04-15 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='yclients_config', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_id', models.PositiveIntegerField()),
                ('bearer_token', models.CharField(max_length=255)),
                ('user_token', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Configuration',
            },
        ),
    ]
