CREATE TABLE "Weeks" (
	"Id"	INTEGER NOT NULL DEFAULT 1 PRIMARY KEY AUTOINCREMENT UNIQUE,
	"CustomerId"	INTEGER NOT NULL,
	"Since"	TEXT NOT NULL,
	"Till"	TEXT NOT NULL,
"	Visits"	NUMERIC NOT NULL DEFAULT 0,
	"Payed"	REAL NOT NULL DEFAULT 0,
	FOREIGN KEY("CustomerId") REFERENCES "Customers"("Id")
)